apiVersion: apps/v1
kind: Deployment
metadata:
    name: app1
spec:
    replicas: 5
    selector:
        matchLabels:
            app: app1
    template:
        metadata:
            labels:
                app: app1
        spec:
            containers:
                - name: app1
                  image: jp.icr.io/invento/app1
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 5000
                        protocol: TCP
